#!/bin/bash

for _schema in $(echo ${DB_SCHEMAS} | sed "s/,/ /g")
do
	mkdir -p /db-dumps/${_schema}
	cp temp.sh ${_schema}-dump.sh
	sed -i 's/DB_PORT_R/'${DB_PORT}'/g' ${_schema}-dump.sh
	sed -i 's/DB_HOST_R/'${DB_HOST}'/g' ${_schema}-dump.sh
	sed -i 's/DB_USER_R/'${DB_USER}'/g' ${_schema}-dump.sh
	sed -i 's/DB_PASS_R/'${DB_PASS}'/g' ${_schema}-dump.sh
	sed -i 's/SCHEMA_R/'${_schema}'/g' ${_schema}-dump.sh
    echo "0 3 * * * /usr/src/app/${_schema}-dump.sh >> /var/log/cron.log 2>&1" > /etc/cron.d/${_schema}-dump-cron
    echo "#" >> /etc/cron.d/${_schema}-dump-cron
    chmod 0644 /etc/cron.d/${_schema}-dump-cron
    crontab /etc/cron.d/${_schema}-dump-cron
done

cron start && tail -f /var/log/cron.log